version: '3.8'

services:
  core-api:
    container_name: core-api
    build: 
      context: .
      dockerfile: Dockerfile.dev
    env_file: ./.env.dev
    ports:
      - "$PORT:$PORT"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - redis
      - mongo
    restart: unless-stopped

  redis:
    container_name: redis-suryadt
    image: redis:7-alpine
    env_file: ./.env.dev
    ports:
      - "$REDIS_PORT:$REDIS_PORT"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  mongo:
    container_name: mongodb-suryadt
    image: mongo:7
    env_file: ./.env.dev
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$DB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$DB_PASSWORD
    ports:
      - "$MONGODB_PORT:$MONGODB_PORT"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - core-api
    restart: unless-stopped

volumes:
  redis_data:
  mongo_data: